% Nonlinear SEIR model
% 

function [pns] = simple_pn_Nonlin_SIR_pdf()
global global_info

pns.PN_name = 'Nonlin_SIR: variable arc weights ';
pns.set_of_Ps = {'pSusceptible','pExposed','pInfected','pRecovered'};
pns.set_of_Ts = {'t_1','t_2','t_3','t_4','t_5','t_6','t_7','t_8'}; 
pns.set_of_As = {...
 't_1','pSusceptible', global_info.t_1_pSus,... 
 'pSusceptible','t_2', global_info.pSus_t_2,... 
 'pExposed','t_4', global_info.pExp_t_4,... 
 'pInfected','t_6', global_info.pInf_t_6,... 
 'pRecovered','t_8',global_info.pRec_t_8,... 
 'pSusceptible','t_3',global_info.pSus_t_3,... 
 't_3','pExposed',global_info.t_3_pExp,... 
 'pExposed','t_5',global_info.pExp_t_5,...
 't_5','pInfected',global_info.t_5_pInf,... 
 'pInfected','t_7',global_info.pInf_t_7,... 
 't_7','pRecovered',global_info.t_7_pRec,... 
  };    
